# Generated by Django 4.0.5 on 2022-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_rename_events_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coverImg',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_id',
            field=models.IntegerField(),
        ),
    ]
