# Generated by Django 4.0.5 on 2022-07-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingPage', '0006_alter_event_coverimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('dateOfBirth', models.DateField()),
                ('rating', models.FloatField()),
                ('event', models.ManyToManyField(blank=True, related_name='users', to='landingPage.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userData', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
