# Generated by Django 4.0.5 on 2022-07-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0007_data_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_user',
            name='dateOfBirth',
        ),
    ]
