# Generated by Django 4.0.5 on 2022-07-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0008_remove_data_user_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_user',
            name='rating',
        ),
    ]
