# Generated by Django 4.0.5 on 2022-07-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0010_remove_booking_event_id_remove_data_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='data_user',
            name='event',
        ),
        migrations.RemoveField(
            model_name='data_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='event',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_value',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
