# Generated by Django 4.0.5 on 2022-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0012_booking_event_booking_user_data_user_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_value',
            field=models.IntegerField(null=True),
        ),
    ]
