# Generated by Django 4.0.5 on 2022-07-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0013_rating_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
