# Generated by Django 4.0.5 on 2022-07-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0014_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
