# Generated by Django 4.0.5 on 2022-07-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0017_alter_rating_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='rating',
            order_with_respect_to=None,
        ),
    ]
