# Generated by Django 4.0.5 on 2022-07-18 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingPage', '0019_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingAdmin',
        ),
    ]
