# Generated by Django 4.0.5 on 2022-07-18 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingPage', '0020_rename_rating_ratingadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingAdmin',
            new_name='Rating',
        ),
    ]
