# Generated by Django 4.0.5 on 2022-07-18 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0024_alter_rating_unique_together_rating_star_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
