# Generated by Django 4.0.5 on 2022-07-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0026_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
